'use client'

import { useEffect, useState } from 'react'
import { Plus, Save } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

export function OrderSupplies({ showNotice }: { showNotice: (message: string) => void }) {
  const [businessId, setBusinessId] = useState<string | null>(null)
  const [rows, setRows] = useState<any[]>([])
  const [form, setForm] = useState({ supplierName: '', supplierPhone: '', orderNumber: '', productName: '', quantity: '', batchNumber: '', expiryDate: '' })
  const supabase = createClient()
  useEffect(() => { void (async () => { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return; const { data: profile } = await supabase.from('profiles').select('business_id').eq('user_id', auth.user.id).maybeSingle(); if (!profile?.business_id) return; setBusinessId(profile.business_id); const { data } = await supabase.from('order_supplies').select('id,supplier_name,supplier_phone,order_number,product_name,quantity,batch_number,expiry_date,received_at').eq('business_id', profile.business_id).order('received_at', { ascending: false }); setRows(data ?? []) })() }, [supabase])
  const save = async () => { if (!businessId || !form.supplierName.trim() || !form.productName.trim() || Number(form.quantity) <= 0) return showNotice('Supplier, product and quantity are required'); const { data, error } = await supabase.from('order_supplies').insert({ business_id: businessId, supplier_name: form.supplierName.trim(), supplier_phone: form.supplierPhone.trim() || null, order_number: form.orderNumber.trim() || null, product_name: form.productName.trim(), quantity: Number(form.quantity), batch_number: form.batchNumber.trim() || null, expiry_date: form.expiryDate || null }).select('id,supplier_name,supplier_phone,order_number,product_name,quantity,batch_number,expiry_date,received_at').single(); if (error) return showNotice('Could not save supply receipt'); setRows(current => [data, ...current]); setForm({ supplierName: '', supplierPhone: '', orderNumber: '', productName: '', quantity: '', batchNumber: '', expiryDate: '' }); showNotice('Order supply recorded') }
  return <section><div className="mb-8 flex items-end justify-between"><div><div className="mb-3 inline-flex rounded-full bg-[#e8f4e8] px-3 py-1 text-[10px] font-bold uppercase tracking-[0.14em] text-[#39724a]">Inventory receiving</div><h1 className="text-[30px] font-bold tracking-[-0.05em]">Order supplies</h1><p className="mt-2 text-sm text-[#7d8980]">Record supplier, batch, expiry and received quantity for every delivery.</p></div><button onClick={save} className="flex items-center gap-2 rounded-xl bg-[#2f7047] px-4 py-2.5 text-sm font-semibold text-white"><Save className="size-4" /> Save receipt</button></div><div className="rounded-[22px] border border-[#e3ebe2] bg-white p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['supplierName','Supplier name'],['supplierPhone','Supplier phone'],['orderNumber','Order number'],['productName','Product name'],['quantity','Quantity received'],['batchNumber','Batch number']].map(([key,label]) => <label key={key} className="text-xs font-semibold text-[#647269]">{label}<input value={(form as any)[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} className="mt-1 h-10 w-full rounded-lg border px-3 text-sm" /></label>)}<label className="text-xs font-semibold text-[#647269]">Expiry date<input type="date" value={form.expiryDate} onChange={e => setForm({ ...form, expiryDate: e.target.value })} className="mt-1 h-10 w-full rounded-lg border px-3 text-sm" /></label></div></div><div className="mt-5 overflow-x-auto rounded-[22px] border border-[#e3ebe2] bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#f8faf7] text-xs text-[#758278]"><tr>{['Received','Supplier','Order','Product','Quantity','Batch','Expiry'].map(head => <th key={head} className="px-4 py-3 font-semibold">{head}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-t"><td className="px-4 py-3">{new Date(row.received_at).toLocaleString('en-NG')}</td><td className="px-4 py-3">{row.supplier_name}</td><td className="px-4 py-3">{row.order_number || '—'}</td><td className="px-4 py-3 font-medium">{row.product_name}</td><td className="px-4 py-3">{row.quantity}</td><td className="px-4 py-3">{row.batch_number || '—'}</td><td className="px-4 py-3">{row.expiry_date || '—'}</td></tr>)}</tbody></table>{!rows.length && <div className="p-8 text-center text-sm text-[#89958c]">No supplies received yet.</div>}</div></section>
}
