'use client'

import { useMemo, useState } from 'react'
import { ExternalLink, ImagePlus, PackagePlus, Search, ShoppingBag, Tag, Truck, Upload, X } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

type Product = { id: string; name: string; category: string; sku: string; price: number; compareAt: number; stock: number; published: boolean; type: 'Product' | 'Service' }
const seed: Product[] = [
  { id: '1', name: 'Golden Penny Spaghetti', category: 'Groceries', sku: 'GP-SPAG-500', price: 850, compareAt: 1000, stock: 42, published: true, type: 'Product' },
  { id: '2', name: 'Peak Milk 400g', category: 'Dairy', sku: 'PEAK-400', price: 3200, compareAt: 3200, stock: 8, published: true, type: 'Product' },
  { id: '3', name: 'Weekend Lagos Food Tour', category: 'Services', sku: 'TOUR-LAG-01', price: 75000, compareAt: 75000, stock: 20, published: false, type: 'Service' },
]
const money = (value: number) => `₦${value.toLocaleString('en-NG')}`

export function StoreManagement({ businessName, showNotice }: { businessName: string; showNotice: (message: string) => void }) {
  const [tab, setTab] = useState<'products' | 'orders' | 'settings' | 'analytics'>('products')
  const [products, setProducts] = useState(seed)
  const [query, setQuery] = useState('')
  const [showForm, setShowForm] = useState(false)
  const [form, setForm] = useState({ name: '', category: 'Groceries', price: '', stock: '', type: 'Product' as Product['type'] })
  const filtered = useMemo(() => products.filter(product => `${product.name} ${product.sku} ${product.category}`.toLowerCase().includes(query.toLowerCase())), [products, query])
  const addProduct = async () => {
    if (!form.name.trim() || !form.price) return showNotice('Add a product name and price')
    const product: Product = { id: crypto.randomUUID(), name: form.name.trim(), category: form.category, sku: `WEB-${Date.now()}`, price: Number(form.price), compareAt: Number(form.price), stock: Number(form.stock || 0), published: true, type: form.type }
    setProducts(current => [product, ...current]); setShowForm(false); setForm({ name: '', category: 'Groceries', price: '', stock: '', type: 'Product' }); showNotice('Store product added')
    await createClient().from('products').insert({ name: product.name, sku: product.sku, category: product.category, price: product.price, stock_count: product.stock, published: product.published })
  }
  return <section>
    <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-3 inline-flex rounded-full bg-[#e8f4e8] px-3 py-1 text-[10px] font-bold uppercase tracking-[0.14em] text-[#39724a]">Online store</div><h1 className="text-[30px] font-bold tracking-[-0.05em] text-[#183022]">Sell online from {businessName}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#7d8980]">Manage products, orders, delivery and storefront settings without leaving your workspace.</p></div><a href={`/store/${businessName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2 rounded-xl bg-[#2f7047] px-4 py-2.5 text-sm font-semibold text-white"><ExternalLink className="size-4" /> View storefront</a></div>
    <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Store revenue" value="₦428,500" detail="+18.4% this month" /><Metric label="Orders" value="38" detail="12 awaiting action" /><Metric label="Visitors" value="2,841" detail="Last 30 days" /><Metric label="Conversion" value="3.8%" detail="+0.6% this month" /></div>
    <div className="mb-6 flex flex-wrap gap-2 rounded-2xl border border-[#e3ebe2] bg-white p-2">{[['products', PackagePlus, 'Products'], ['orders', Truck, 'Orders'], ['analytics', ShoppingBag, 'Analytics'], ['settings', Tag, 'Store settings']].map(([value, Icon, label]) => <button key={value as string} onClick={() => setTab(value as typeof tab)} className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold ${tab === value ? 'bg-[#e6f3e7] text-[#2f7047]' : 'text-[#748077] hover:bg-[#f5faf4]'}`}><Icon className="size-4" />{label as string}</button>)}</div>
    {tab === 'products' && <div className="rounded-[22px] border border-[#e3ebe2] bg-white p-5"><div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="font-bold text-[#1d2b22]">Products & services</h2><p className="mt-1 text-sm text-[#7d8980]">Publish products, experiences, packages and services.</p></div><div className="flex gap-2"><label className="flex cursor-pointer items-center gap-2 rounded-xl border border-[#d8e5d8] px-3 py-2 text-xs font-semibold text-[#39724a]"><Upload className="size-4" /> CSV upload<input type="file" accept=".csv" className="sr-only" onChange={() => showNotice('CSV upload queued for review')} /></label><button onClick={() => setShowForm(true)} className="flex items-center gap-2 rounded-xl bg-[#2f7047] px-3 py-2 text-xs font-semibold text-white"><PackagePlus className="size-4" /> Add item</button></div></div><label className="mb-4 flex items-center gap-2 rounded-xl border border-[#d8e5d8] px-3 py-2 text-sm text-[#7d8980]"><Search className="size-4" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search products, SKU or category" className="w-full bg-transparent outline-none" /></label><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-[#edf1eb] text-xs uppercase tracking-[0.1em] text-[#9aa49c]"><tr><th className="pb-3">Item</th><th className="pb-3">Category</th><th className="pb-3">Price</th><th className="pb-3">Stock</th><th className="pb-3">Status</th><th /></tr></thead><tbody>{filtered.map(product => <tr key={product.id} className="border-b border-[#f0f4ef]"><td className="py-4"><div className="font-semibold text-[#1d2b22]">{product.name}</div><div className="mt-1 text-xs text-[#9aa49c]">{product.sku} · {product.type}</div></td><td>{product.category}</td><td className="font-semibold">{money(product.price)}{product.compareAt > product.price && <span className="ml-2 text-xs text-[#9aa49c] line-through">{money(product.compareAt)}</span>}</td><td>{product.stock}</td><td><button onClick={() => setProducts(current => current.map(item => item.id === product.id ? { ...item, published: !item.published } : item))} className={`rounded-full px-2.5 py-1 text-xs font-semibold ${product.published ? 'bg-[#e8f4e8] text-[#39724a]' : 'bg-[#f4eee6] text-[#a66b2b]'}`}>{product.published ? 'Published' : 'Draft'}</button></td><td><button onClick={() => { setProducts(current => current.filter(item => item.id !== product.id)); showNotice('Item removed') }} aria-label={`Remove ${product.name}`}><X className="size-4 text-[#9aa49c]" /></button></td></tr>)}</tbody></table></div></div>}
    {tab === 'orders' && <div className="grid gap-4 lg:grid-cols-3"><OrderStatus title="New" count="12" items={['Order #WEB-1048', 'Order #WEB-1047']} /><OrderStatus title="Packing" count="4" items={['Order #WEB-1042', 'Order #WEB-1039']} /><OrderStatus title="Delivered" count="22" items={['Order #WEB-1038', 'Order #WEB-1035']} /></div>}
    {tab === 'analytics' && <div className="grid gap-4 lg:grid-cols-2"><Insight title="Top products" items={['Golden Penny Spaghetti · 48 sold', 'Peak Milk 400g · 32 sold', 'Weekend Lagos Food Tour · 9 booked']} /><Insight title="Revenue by day" items={['Mon · ₦42,000', 'Tue · ₦68,500', 'Wed · ₦51,000', 'Thu · ₦74,500']} /></div>}
    {tab === 'settings' && <div className="grid gap-4 lg:grid-cols-2"><SettingCard icon={Truck} title="Delivery zones" description="Configure Lagos, pickup and custom delivery fees." /><SettingCard icon={Tag} title="Coupons & discounts" description="Create free-delivery thresholds, flash sales and promo codes." /><SettingCard icon={ShoppingBag} title="Payment methods" description="Enable pay on delivery, bank transfer and gateway checkout." /><SettingCard icon={Upload} title="Store availability" description="Keep your storefront open or temporarily closed." /></div>}
    {showForm && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#183022]/30 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold">Add store item</h2><p className="mt-1 text-sm text-[#7d8980]">Products and services use the same catalogue.</p></div><button onClick={() => setShowForm(false)} aria-label="Close"><X className="size-5" /></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="Name" className="h-11 rounded-xl border px-3 sm:col-span-2" /><input value={form.category} onChange={event => setForm({ ...form, category: event.target.value })} placeholder="Category" className="h-11 rounded-xl border px-3" /><select value={form.type} onChange={event => setForm({ ...form, type: event.target.value as Product['type'] })} className="h-11 rounded-xl border px-3"><option>Product</option><option>Service</option></select><input value={form.price} onChange={event => setForm({ ...form, price: event.target.value })} type="number" placeholder="Price" className="h-11 rounded-xl border px-3" /><input value={form.stock} onChange={event => setForm({ ...form, stock: event.target.value })} type="number" placeholder="Stock / slots" className="h-11 rounded-xl border px-3" /><label className="flex items-center gap-3 rounded-xl border border-dashed p-3 text-sm text-[#39724a] sm:col-span-2"><ImagePlus className="size-5" /> Add product photos<input type="file" accept="image/*" multiple className="sr-only" /></label></div><button onClick={() => void addProduct()} className="mt-5 w-full rounded-xl bg-[#2f7047] px-4 py-3 text-sm font-semibold text-white">Save item</button></div></div>}
  </section>
}
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-2xl border border-[#e3ebe2] bg-white p-5"><div className="text-xs text-[#89958c]">{label}</div><div className="mt-3 text-2xl font-bold tracking-[-0.04em] text-[#1d2b22]">{value}</div><div className="mt-1 text-xs font-semibold text-[#4d9563]">{detail}</div></div> }
function OrderStatus({ title, count, items }: { title: string; count: string; items: string[] }) { return <div className="rounded-2xl border border-[#e3ebe2] bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold">{title}</h2><span className="rounded-full bg-[#e8f4e8] px-2 py-1 text-xs font-bold text-[#39724a]">{count}</span></div><div className="mt-4 flex flex-col gap-2">{items.map(item => <div key={item} className="rounded-xl bg-[#f7fbf6] p-3 text-sm font-semibold">{item}<div className="mt-1 text-xs font-normal text-[#89958c]">Awaiting staff action</div></div>)}</div></div> }
function Insight({ title, items }: { title: string; items: string[] }) { return <div className="rounded-2xl border border-[#e3ebe2] bg-white p-5"><h2 className="font-bold">{title}</h2><div className="mt-4 flex flex-col gap-2">{items.map(item => <div key={item} className="rounded-xl bg-[#f7fbf6] p-3 text-sm">{item}</div>)}</div></div> }
function SettingCard({ icon: Icon, title, description }: { icon: typeof Truck; title: string; description: string }) { return <button className="flex items-start gap-4 rounded-2xl border border-[#e3ebe2] bg-white p-5 text-left hover:border-[#a9cda9]"><span className="flex size-10 items-center justify-center rounded-xl bg-[#e8f4e8] text-[#39724a]"><Icon className="size-5" /></span><span><b>{title}</b><span className="mt-1 block text-sm leading-6 text-[#7d8980]">{description}</span></span></button> }
